### ISSUE TITLE
Bad exception handling

### ISSUE THREAD

**Issue by Rizhiy** [MG2033/MobileNet-V2#1]
https://github.com/MG2033/MobileNet-V2/blob/508d824111d98fb60b2d313366885fc764ce40fd/main.py#L10-L14

This is quite bad code style, you need to provide more information.
e.g. it will catch errors if the config file doesn't exist or if the config file can't be processed.

**Comment by Rizhiy** [comment]
More importantly I get the following error:
```python
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    main()
  File "main.py", line 10, in main
    config_args = parse_args()
  File "/home/rizhiy/misc_repos/MobileNet-V2/utils.py", line 28, in parse_args
    print(config_args)
  File "/home/rizhiy/miniconda3/envs/MobileNet-V2/lib/python3.6/site-packages/bunch/__init__.py", line 200, in __repr__
    keys.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```

**Comment by MG2033** [comment]
Thank you for pointing that out. I'll update the exception message. However, I don't know why you get that error except that "bunch" is not compatible with python 3.6.

**Comment by Rizhiy** [comment]
That must be the problem as I'm using python3.6.
Why are you using `bunch` instead of `easydict`?
`Bunch` hasn't been updated in 5 years.

**Comment by MG2033** [comment]
I've used it for nearly 3 years and I've not found any issues with it. I thought it gets updated regularly. I'll move to "easydict" or another library. Thank you again.

**Comment by MG2033** [comment]
I updated the code. Check it out, please.

**Comment by Rizhiy** [comment]
Thanks.

I have added more fine-grained inception handling, check it out please: #2
